name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        pod install --repo-update
      shell: bash
    - name: Build
      run: xcodebuild -workspace FitNess.xcworkspace -scheme FitNess -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
    - name: Test
      run: xcodebuild -workspace FitNess.xcworkspace -scheme FitNess -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' test
