name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Testing iOS app
      run: xcodebuild -workspace Fitness.xcworkspace \
            -scheme FitNess\ iOS \
            -destination platform=iOS\ Simulator,OS=14.1,name=iPhone\ 8 \
            clean test | xcpretty
